# Generated by Django 5.1.2 on 2024-10-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(max_length=2)),
                ('material', models.CharField(max_length=64)),
                ('Lining', models.CharField(max_length=64)),
                ('Insole', models.CharField(max_length=64)),
                ('Sole', models.CharField(max_length=64)),
            ],
        ),
    ]
