# Generated by Django 5.1.2 on 2024-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shoes_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(default=0, upload_to='images/%Y/%m/%d/items'),
            preserve_default=False,
        ),
    ]
