# Generated by Django 5.1.2 on 2024-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shoes_insole_alter_shoes_lining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='Insole',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='Lining',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='Sole',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='material',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shoes',
            name='insole',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shoes',
            name='lining',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sole',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
